fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # use the ref you want to point at
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version. run `uv self update` and match it
    rev: 0.9.16
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # uv run ruff --version
    rev: v0.15.2
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/RobertCraigie/pyright-python
    # uv run pyright --version
    rev: v1.1.408
    hooks:
      - id: pyright
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.2
    hooks:
      - id: nbstripout
        name: Check for Jupyter notebook output
        args: [--verify]
  - repo: https://github.com/Yelp/detect-secrets
    # use the ref you want to point at
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: uv.lock
